### ISSUE TITLE
Create Chrome Extension for Shoto.at

### ISSUE THREAD

**Issue by teoh4770** [juancwu/shoto#38]
### Shoto.at Browser Extension Feature

- [ ] Show the links that you have created in your Shoto account (for sharing)
- [ ] Have a link to navigate to the Shoto.at website
- [ ] Have the ability to create a custom link in your current page directly, without copying and pasting (without manual work)

**Comment by juancwu** [comment]
Browser extension is being developed in another repository https://github.com/juancwu/shoto-browser-ext

**Comment by juancwu** [comment]
Not going to be supported.
